# Generated by Django 4.2.3 on 2023-07-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('projectName', models.CharField(max_length=100)),
                ('projectType', models.CharField(max_length=100)),
                ('developerName', models.CharField(max_length=200)),
                ('landParcel', models.PositiveIntegerField()),
                ('landmark', models.CharField(max_length=100)),
                ('areaIn', models.CharField(max_length=100)),
                ('waterSupply', models.CharField(max_length=100)),
                ('floors', models.PositiveIntegerField()),
                ('flatsPerFloors', models.PositiveIntegerField()),
                ('totalUnit', models.PositiveIntegerField()),
                ('availableUnit', models.PositiveIntegerField()),
                ('amenities', models.CharField(max_length=200)),
                ('parking', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('transport', models.BooleanField()),
                ('readyToMove', models.BooleanField()),
                ('power', models.BooleanField()),
                ('goods', models.BooleanField()),
                ('rera', models.DateTimeField()),
                ('possession', models.DateTimeField()),
                ('contactPerson', models.CharField(max_length=100)),
                ('contactNumber', models.PositiveIntegerField()),
                ('marketValue', models.FloatField()),
                ('lifts', models.PositiveIntegerField()),
                ('brokerage', models.FloatField()),
                ('incentive', models.PositiveIntegerField()),
                ('bhk', models.FloatField()),
                ('carpetArea', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
