# Generated by Django 4.2.3 on 2023-07-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0004_rename_area_project_area_remove_project_amenities_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unit',
            new_name='Units',
        ),
    ]
