# Generated by Django 4.2.3 on 2023-07-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0008_rename_project1_project_rename_unit1_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='project_id',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
