# Generated by Django 4.2.3 on 2023-07-22 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.FloatField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='home_API.project1')),
            ],
        ),
    ]
