# Generated by Django 4.2.3 on 2023-07-23 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0011_unit1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('projectName', models.CharField(max_length=100)),
                ('projectType', models.CharField(max_length=100)),
                ('developerName', models.CharField(max_length=100)),
                ('landParcel', models.FloatField()),
                ('landmark', models.CharField(max_length=100)),
                ('areaIn', models.CharField(max_length=100)),
                ('waterSupply', models.CharField(max_length=100)),
                ('floors', models.IntegerField()),
                ('flatsPerFloors', models.IntegerField()),
                ('totalUnit', models.IntegerField()),
                ('availableUnit', models.IntegerField()),
                ('amenities', models.CharField(max_length=100)),
                ('parking', models.CharField(max_length=100)),
                ('location_longitude', models.FloatField()),
                ('location_latitude', models.FloatField()),
                ('transport', models.BooleanField()),
                ('readyToMove', models.BooleanField()),
                ('power', models.BooleanField()),
                ('goods', models.BooleanField()),
                ('rera', models.DateTimeField()),
                ('possession', models.DateTimeField()),
                ('contactPerson', models.CharField(max_length=100)),
                ('contactNumber', models.IntegerField()),
                ('marketValue', models.IntegerField()),
                ('lifts', models.IntegerField()),
                ('brokerage', models.FloatField()),
                ('incentive', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.FloatField()),
                ('CarpetArea', models.IntegerField(max_length=100)),
                ('price', models.IntegerField(max_length=100)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='home_API.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='unit1',
            name='project_id',
        ),
        migrations.DeleteModel(
            name='Project1',
        ),
        migrations.DeleteModel(
            name='Unit1',
        ),
    ]
