# Generated by Django 4.2.3 on 2023-07-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0012_project_unit_remove_unit1_project_id_delete_project1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='CarpetArea',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='price',
            field=models.IntegerField(),
        ),
    ]
