# Generated by Django 4.2.3 on 2023-07-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0013_alter_unit_carpetarea_alter_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='location_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='location_longitude',
            new_name='longitude',
        ),
    ]
